### ISSUE TITLE
Inherit flags

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/next-ab#27]
- [ ] Flags have isAbTest property.
- [ ] next-ab fetches flags every 60 seconds and exposes non-expired tests.
- [ ] Add 'ab test purpose' to flags
- [ ] Highlight in __toggler the running AB tests

**Comment by wheresrhys** [comment]
I think there is a bug with expiry too as the prominent follow flag expired a while ago https://github.com/Financial-Times/next-feature-flags-api/blob/master/models/flags.js#L582, but if someone was originally placed in the 'on' bucket then this appears to persist beyond the life of either the flag or the ab test

**Comment by commuterjoy** [comment]
In the cookie? You might have toggled this yourself?
